/*
 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 analytics.js v1.0
 Created: 2021-01-27T18:51:04+0000
*/
(function(m,k){if(!m.ORA.analytics){var c=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PRODUCT_READY,ORA.Event.STATUS_SUCCESS));ORA.common.TrackingPipeline.productIsReady("analytics");ORA.Debug.debug("setProductReady()","ANA")},d=function(b){return!(-1!==k.cookie.indexOf(b.FPCConfig.name+"\x3d")||-1!==k.cookie.indexOf(b.FPCConfig.legacyCName+"\x3d")||ORA.analytics.isOptedOut()||!b.FPCConfig.enabled)};ORA.analytics={dcsRef:null,plugins:{},addEventListener:ORA.addDOMEvent,eventQueue:null,version:{major:1,
minor:0,inc:4},versionStr:"1.0.4",qryparams:{},dcsdelay:25,productReadyLatch:{},elemOfEvent:function(b,a){var f=b.target||b.srcElement,e=a||{};"string"===typeof a&&(e={},e[a.toUpperCase()]=1);for(;f&&f.tagName&&!e[f.tagName.toUpperCase()];)f=f.parentElement||f.parentNode;return f},multiTrack:function(b){try{return ORA.analytics.dcsRef.dcsMultiTrack(b),!1}catch(a){throw ORA.Debug.error("Error ORA.analytics.multiTrack: "+a.toSource(),"ANA"),a;}},instantiateExternal:function(){ORA.analytics.qryparams=
ORA.common.QueryParamCache.getCache();ORA.analytics.loadJS=ORA.common.loadJS;ORA.analytics.eventQueue=new ORA.common.Queue;ORA.analytics.prettify=ORA.common.JSONPrettify;ORA.analytics.dcsSaveCookie=ORA.common._setCookie;ORA.analytics.dcsDeleteCookie=ORA.common._deleteCookie;ORA.analytics.extendArray=ORA.common.extendArray;ORA.analytics.isFn=ORA.common.isFn;ORA.analytics.isArray=ORA.common.isArray;ORA.analytics.getCookieAsObj=ORA.common._getCookieAsObj;ORA.analytics.isEmpty=ORA.common.isEmpty;ORA.analytics.click=
ORA.click;ORA.analytics.view=ORA.view;ORA.analytics.collect=ORA.collect;ORA.analytics.regPlugin=ORA.regPlugin;ORA.analytics.getTagId=ORA.getTagId;ORA.analytics.getContextName=ORA.getContextName;ORA.analytics.getPluginsConfig=ORA.analytics._getPluginsConfig;ORA.analytics.setCookie=ORA.common._setCookie;ORA.analytics.deleteCookie=ORA.common._deleteCookie;ORA.analytics.getCookieRaw=ORA.common._getCookieRaw;ORA.analytics.getIEVer=ORA.common._getIEVer;ORA.analytics.isOptedOut=ORA.common._isOptedOut;ORA.analytics.setInfinityOptOut=
ORA.common._setInfinityOptOut;ORA.analytics.addMutation=ORA.analytics.addMutation;ORA.analytics.rmMutation=ORA.analytics.rmMutation;ORA.analytics.getFPC=function(){var b=ORA.analytics.getCookieAsObj(ORA.analytics.dcsRef.FPCConfig.name);return b&&b.id?b.id:null}},reset:function(){ORA.Debug.info("Analytics reset()","ANA");ORA.analytics.dscRef={}},execute:function(b){ORA.Debug.info("Analytics execute()","ANA");ORA.analytics.reset();var a=ORA.analyticsModule.prototype.oraConfigObj;b&&b.params&&ORA.hasVal(b.params)?
(b=ORA.common.getMergedConfigs(a,b.params),ORA.analytics.setup(b)):ORA.analytics.setup(a)},registerLoaderEvents:function(){ORA.addEventHandler(ORA.Event.LOADER_RESET,this.reset);ORA.addEventHandler(ORA.Event.LOADER_EXECUTE,this.execute)},setupPluginMgr:function(b){var a=ORA.analytics.getPluginCount("ora-plugins"),f=ORA.common.pluginMgr,e=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - ora Plugins Initialized, productReadyLatch.countDown()",
"ANA");ORA.analytics.productReadyLatch.countDown()};0<a?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+a+"), deferring initPluginsCallback until plugins loaded","ANA"),f.setNumExpectedPlugins(a),f.setInitPluginsCallback(e),f.setInjectConfigsCb(ORA.analytics._getPluginsConfig,"ora-plugins")):(0===a&&d(b)?(ORA.Debug.debug("setupPluginMgr - ora pluginCount("+a+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_ORA_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS))):
ORA.Debug.debug("setupPluginMgr - ora pluginCount("+a+"), not waiting on getId so countDown immediately","ANA"),e());f.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_ORA_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS));f=ORA.analytics.getPluginCount("hosted-plugins");var g=ORA.common.hostedPluginMgr,h=function(){ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("setupPluginMgr - Hosted Plugins Initialized, productReadyLatch.countDown()","ANA");
ORA.analytics.productReadyLatch.countDown()};0<f?(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+f+"), deferring initPluginsCallback until plugins loaded","ANA"),g.setNumExpectedPlugins(f),g.setInitPluginsCallback(h),g.setInjectConfigsCb(ORA.analytics._getPluginsConfig),g.processHostedPlugins(b.config["hosted-plugins"])):0===f&&d(b)?(ORA.Debug.debug("setupPluginMgr - hosted pluginCount("+a+"), now waiting on getId, so wait to countDown latch ","ANA"),ORA.fireEvent(new ORA.Event(ORA.Event.ANA_HOSTED_PLUGINS_INIT,
ORA.Event.STATUS_SUCCESS)),e()):(ORA.Debug.debug("setupPluginMgr - Hosted pluginCount("+a+"), not waiting on getId so countDown immediately","ANA"),h());g.setReady();ORA.fireEvent(new ORA.Event(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,ORA.Event.STATUS_SUCCESS))},setupProductCountdownLatch:function(b){var a=2;d(b)&&(ORA.Debug.trace("prodCountdownLatch: waitForGetIdCall, latchCount++","ANA"),a++);ORA.analytics.productReadyLatch=new ORA.common.CountDownLatchClass(a,c,"ProductReadyLatch");ORA.Debug.debug("set productReadyLatch to "+
a,"ANA")},setCheckSetDisableSeed:function(b){!0===b.s_disableSeed&&ORA.common.TrackingPipeline.disableSeed()},setup:function(b){try{ORA.Debug.debug("Analytics setup() started","ANA");this.instantiateExternal();this.setCheckSetDisableSeed(b);var a=new ORA.analytics.dcs;a.init(b);this.setupProductCountdownLatch(a);a.setup();this.dcsRef=a;this.setupPluginMgr(this.dcsRef);this.registerLoaderEvents();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_SETUP_COMPLETE,ORA.Event.STATUS_SUCCESS));ORA.Debug.debug("Analytics setup() has finished",
"ANA")}catch(f){ORA.Debug.error("Analytics setup() failure",201,f,"ANA")}},addMutation:function(b,a,f){return ORA.common.TrackingPipeline.registerMutation(b,a,f?f:2)},rmMutation:function(b){return ORA.common.TrackingPipeline.deregisterMutation(b)},getProductTimeout:function(){return ORA.common.TrackingPipeline.getProduct("analytics").timeout},_getPluginsConfig:function(b,a){var f={};ORA.analyticsModule.prototype.oraConfigObj[a]&&ORA.analyticsModule.prototype.oraConfigObj[a][b]&&(f=ORA.analyticsModule.prototype.oraConfigObj[a][b]);
return f},getPluginCount:function(b){return ORA.analyticsModule.prototype.oraConfigObj[b]?ORA.common.extendObject(ORA.analyticsModule.prototype.oraConfigObj[b]).length():0},getConfigParams:function(){var b=ORA.analytics,a={},f=ORA.analytics.dcsRef;f&&ORA.common.extendArray(["accountGuid","destinations","enabled","i18n","timezone"]).forEach(function(e){f[e]&&(a[e]=f[e])});a.version=b.version;a.versionStr=[a.version.major,a.version.minor,a.version.inc].join(".");a.dcsdelay=b.dcsdelay;return a}};ORA.Debug.debug("ORA.analytics instantiation success",
"ANA")}})(window,window.document);
(function(m,k){ORA.analytics.dcs=function(){var c=m.RegExp?/dcs(uri)|(ref)|(aut)|(met)|(sta)|(sip)|(pro)|(byt)|(dat)|(p3p)|(cfg)|(redirect)|(cip)/i:"";this.exre=c;this.re={};this.plugins=this.plugins={};this.trackingData=this.trackingData={};this.DCS=this.DCS={};this.destinations=[];this.DCSext=this.DCSext={};this.errors=this.errors=[];this.FPCConfig=this.FPCConfig={};this._onsitedoms=[];this.gTempWtId=this.gWtAccountRollup=this.oraId="";this.prettify=ORA.analytics.prettify;return this};ORA.analytics.dcs.prototype=
{init:function(c){var d=c;try{ORA.Debug.debug("dcs init() start","ANA");"undefined"===typeof d&&(d={});this.config=d;var b=this;c=function(e,g){return d.hasOwnProperty(e)?d[e]:g};var a=function(e,g,h){return e?e.hasOwnProperty(g)?e[g]:h:h};this.extendArray=ORA.common.extendArray;this.errorlogger=function(e){ORA.Debug.error("Dcs",100,e,"ANA")};d.defaultCollectionServer||ORA.Debug.error("dcs init:  missing defaultCollectionServer");this.destinations=this.destinations=function(e){if(!e||0===e.length)throw Error("Destinations are not configured");
for(var g=[],h=0;h<e.length;h++){var l=a(e[h],"collectionServer",d.defaultCollectionServer),n={};n.collectionServer=n.collectionServer=l;n.timeout=n.timeout=a(e[h],"timeout",2E3);n.accountGuid=n.accountGuid=e[h].accountGuid;n.endpoint=n.endpoint=b.collectionEndpoint(l,e[h].accountGuid);g.push(n)}return g}(d.destinations);this.accountGuid=this.accountGuid=this.destinations[0].accountGuid;this.queue=this.queue=c("queue",[]);this.wtidTimeout=c("wtidTimeout",1E3);this.timezone=this.timezone=c("timezone",
-8);this.enabled=this.enabled=c("enabled",!0);this.i18n=this.i18n=c("i18n",!1);this.re=m.RegExp?b.i18n?{"%25":/%/g,"%26":/&/g,"%23":/#/g}:{"%25":/%/g,"%09":/\t/g,"%20":/\x20|\xA0|\x7F/g,"%23":/#/g,"%26":/&/g,"%2B":/\+/g,"%3F":/\?/g,"%5C":/\\/g,"%22":/"/g}:"";if(d.metanames){var f=d.metanames.toLowerCase();this.metanames=ORA.common.extendArray(f.split(","))}if(!0===d.metatagAuto||"true"===d.metatagAuto)this.metatagAuto=!0;this.skip_qp_no_value=this.skip_qp_no_value=c("skip_qp_no_value",!1);this.skip_qp_no_equals=
this.skip_qp_no_equals=c("skip_qp_no_equals",!1);this.skip_qp=this.skip_qp=c("skip_qp",!1);this.vtid=this.vtid=c("vtid",void 0);this.paidsearchparams=c("paidsearchparams","gclid");ORA.analytics.dcsdelay=d.dcsdelay||ORA.analytics.dcsdelay;this.delayAll=this.delayAll=c("delayAll",!1);this.preserve=this.preserve=c("preserve",!0);this._onsitedoms=c("onsitedoms","");ORA.common.isFn(this._onsitedoms.test)||(this._onsitedoms=ORA.common.extendArray(this._onsitedoms.toLowerCase().split(",")),this._onsitedoms.forEach(function(e,
g,h){h[g]=e.replace(/^\s*/,"").replace(/\s*$/,"")}));c("adimpressions",!1)&&(this.adclickparam=c("adsparam","WT.ac"));this.FPCConfig.enabled=this.FPCConfig.enabled=a(d.FPCConfig,"enabled",!0);this.FPCConfig.domain=this.FPCConfig.domain=a(d.FPCConfig,"domain","");this.FPCConfig.name=this.FPCConfig.name=a(d.FPCConfig,"name","ORA_FPC");this.FPCConfig.optOutCName=this.FPCConfig.optOutCName=a(d.FPCConfig,"optOutCName","Infinity.optout");this.FPCConfig.legacyCName=this.FPCConfig.legacyCName=a(d.FPCConfig,
"legacyCName","WT_FPC");this.FPCConfig.expiry=this.FPCConfig.expiry=a(d.FPCConfig,"expires",63113851500);63113851500<this.FPCConfig.expiry&&(this.FPCConfig.expiry=63113851500);this.FPCConfig.expireDate=new Date(this.getTime()+this.FPCConfig.expiry);this.FPCConfig.sessionOnly=0===this.FPCConfig.expiry||a(d.FPCConfig,"sessionOnly",!1);this.FPCConfig.autoTLD=this.FPCConfig.autoTLD=a(d.FPCConfig,"autoTLD",!1);d.cookieTypes&&(this.FPCConfig.enabled="none"!==d.cookieTypes.toLowerCase());this.plugins=d.plugins||
{};ORA.analytics.dcs.prototype.action_collect=ORA.analytics.dcs.prototype.action_collect;ORA.analytics.dcs.prototype.init=ORA.analytics.dcs.prototype.init;ORA.analytics.dcs.prototype.setup=ORA.analytics.dcs.prototype.setup;ORA.analytics.dcs.prototype.dcsGetIdCallback=ORA.analytics.dcs.prototype.dcsGetIdCallback;ORA.analytics.dcs.prototype.dcsGetFPC=ORA.analytics.dcs.prototype.dcsGetFPC;ORA.analytics.dcs.prototype.dcsGetCookie=ORA.analytics.dcs.prototype.dcsGetCookie;ORA.analytics.dcs.prototype.dcsNavigation=
ORA.analytics.dcs.prototype.dcsNavigation;this.registerProtocol();ORA.Debug.debug("dcs init() finish","ANA");return this}catch(e){throw ORA.Debug.error("Error in init() - "+e.toString()),e;}},registerProtocol:function(){var c=ORA.common.TrackingPipeline;null===c.getCommProtocol(ORA.common.CommManager.GIF)&&(ORA.common._analyticsProtocol=ORA.common.protocols.gifProtocol,c.setCommProtocol(ORA.common.CommManager.GIF,ORA.common._analyticsProtocol))},collectionEndpoint:function(c,d,b){c||ORA.Debug.debug("Warning:  missing collectServer");
c=c?c:"";b=b?b:"dcs.gif";if(!d)throw Error("accountGuid must be configured for "+c);var a=!1;ORA.analyticsModule.prototype.oraConfigObj.hasOwnProperty("disableSSL")&&"boolean"===typeof ORA.analyticsModule.prototype.oraConfigObj.disableSSL&&(a=ORA.analyticsModule.prototype.oraConfigObj.disableSSL);a&&ORA.Debug.debug('SSL is disabled by config setting "disableSSL".');return a?"http://"+c+"/"+d+"/"+b:"https://"+c+"/"+d+"/"+b},dcsGetIdFallback:function(){var c=this;this.id||(this.id=setTimeout(function(){ORA.Debug.debug("client id timeout reached",
"ANA");c.setReady();ORA.analytics.productReadyLatch.countDown();ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS))},this.wtidTimeout));return this.id},dcsGetIdCallback:function(c){if("undefined"!==typeof c){var d={data:{}};try{d=JSON.parse(c)}catch(b){ORA.Debug.debug("dcsGetIdCallback failed, using locally generated guid","ANA")}!this.oraId&&d.data.id&&(this.oraId=d.data.id);ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_GETID,ORA.Event.STATUS_SUCCESS))}this.setReady();
ORA.Debug.debug("dcsGetIdCallback success, productReadyLatch.countDown()","ANA");clearTimeout(this.dcsGetIdFallback());ORA.analytics.productReadyLatch.countDown()},setReady:function(){ORA.Debug.debug("setReady()","ANA");this._readySet||(this.flushqueue(),this.redirectqueue(),this._readySet=!0)},flushqueue:function(){ORA.Debug.trace("flushqueue()","ANA");for(var c=0;c<this.queue.length;c++)this.doAction(this.queue[c]);this.queue=[]},redirectqueue:function(){var c=this;this.queue.push=function(d){c.doAction(d)}},
dcsGetCookie:function(c){return ORA.analytics.dcsGetCookie(c,this.FPCConfig.name)},dcsIsFpcSet:function(c,d){var b=ORA.analytics.getCookieAsObj,a=ORA.analytics.isEmpty;b=b(c);return a(b)?2:d===b.id?0:3},dcsGetFPC:function(){return ORA.analytics.getCookieAsObj(this.FPCConfig.name)},dcsFPC:function(){var c=this.oraId,d=this.oraId,b=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";if(!ORA.analytics.isOptedOut())if(this.FPCConfig.enabled){this.trackingData.ce="1";var a=
this.trackingData,f=this.FPCConfig.name,e=this.FPCConfig.legacyCName,g=new Date,h=6E4*g.getTimezoneOffset()+36E5*this.timezone;g.setTime(g.getTime()+h);var l=new Date(g.getTime());a.co_f=a.vtid="";a.vtvs=a.vt_f="";h=ORA.analytics.getCookieAsObj;var n=ORA.analytics.isEmpty,q=h(f),t=h(e);e=function(){if(n(q)&&n(t))if(c.length)a.co_f=d.length?d:c,a.vt_f="1";else if(d.length)a.co_f=d;else{a.co_f="2";for(var p=g.getTime().toString(),r=2;r<=32-p.length;r++)a.co_f+=Math.floor(16*Math.random()).toString(16);
a.co_f+=p;a.vt_f="1"}else n(q)&&(q=t),p=q.id,null!==p&&(a.co_f=p,g.getTime()>l.getTime()+288E5&&l.setTime(g.getTime()))};if(!ORA.common._isDNTSet()||"honorDNT"!==b){e();a.co_f=escape(a.co_f);a.vtid="undefined"===typeof this.vtid?a.co_f:this.vtid||"";e="";this.FPCConfig.sessionOnly||ORA.common._isDNTSet()&&"anonymize"===b||(e="; expires\x3d"+this.FPCConfig.expireDate.toGMTString());b="";ORA.common._getConfigObject()&&ORA.common._getConfigObject().secureCookie&&"https:"===document.location.protocol.toLowerCase()&&
(b="; secure");h=this.FPCConfig.domain;this.FPCConfig.autoTLD&&!0===this.FPCConfig.autoTLD&&(h=ORA.cookieMgr.checkCookieOnDomainAndGetTLDomain(),this.FPCConfig.domain=h);q.id=a.co_f;ORA.setCookie(f,q,(""!==h?e+"; path\x3d/; domain\x3d"+h:e+"; path\x3d/")+b);this.FPCConfig.sessionOnly?ORA.common.mobile.nativeAppCkSend({name:f,value:q,domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"session",timeout:this.FPCConfig.expiry}):ORA.common.mobile.nativeAppCkSend({name:f,value:q,
domain:this.FPCConfig.domain,date:this.FPCConfig.expireDate,path:"/",type:"persisted",timeout:this.FPCConfig.expiry});f=this.dcsIsFpcSet(f,a.co_f);0!==f&&(a.co_f="","undefined"===typeof this.vtid&&(a.vtid=""),a.vt_f=f);var u={};ORA.common.extendObject(a).forEach(function(p,r){null!==p&&""!==p&&(u["WT."+r]=p)});return u}}else this.trackingData.ce="0",this.trackingData.vtid=this.vtid?this.vtid:"",ORA.analytics.dcsDeleteCookie(this.FPCConfig.name,"/",this.FPCConfig.domain)},setup:function(){try{var c=
ORA.common.clientID.getId,d=this,b=function(e){d.dcsGetIdCallback.apply(d,[e])},a=function(e){d.setReady.apply(d,[]);ORA.Debug.debug("failCallback, productReadyLatch.countDown() "+e);clearTimeout(d.dcsGetIdFallback());ORA.analytics.productReadyLatch.countDown()};if(this.FPCConfig.enabled){var f="https";ORA.analyticsModule.prototype.oraConfigObj.hasOwnProperty("disableSSL")&&"boolean"===typeof ORA.analyticsModule.prototype.oraConfigObj.disableSSL&&ORA.analyticsModule.prototype.oraConfigObj.disableSSL&&
(f="http");ORA.common.mobile.delay(function(){var e={collectionServer:d.destinations[0].collectionServer,accountGuid:d.destinations[0].accountGuid},g=ORA.common._getCookieAsObj(),h=2!==d.dcsIsFpcSet(d.FPCConfig.name),l=ORA.common._getConfigObject()&&ORA.common._getConfigObject().DNTBehavior||"honorDNT";l=ORA.common._isDNTSet()&&"honorDNT"===l;ORA.common._isOptedOut(g)||h||l?d.setReady.apply(d,[]):(c(e,b,a,f),d.dcsGetIdFallback.apply(d,[]))},"ANA",ORA.analyticsModule.prototype.oraConfigObj)}else this.setReady();
this.enQueue("collect",{element:void 0,event:void 0});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_DCS_SETUP,ORA.Event.STATUS_SUCCESS));return this}catch(e){this.errors.push(e),this.errorlogger(e)}},addQueryParameters:function(c,d){var b=this.DCS;if(0<c.length()&&!this.skip_qp){c.forEach(function(e,g){var h=e;if(!((this.skip_qp_no_value||this.skip_qp_no_equals)&&"undefined"===typeof e||this.skip_qp_no_equals&&""===e)){if("undefined"===typeof e||null===e)h="undefined";b[g]=h}},this);var a=this.paidsearchparams.length?
this.paidsearchparams.toLowerCase().split(","):[];for(var f=0;f<a.length;f++)if(ORA.common.QueryParamCache.contains(a[f],!0)){d.srch="1";break}}},dcsVar:function(){var c=this.trackingData;this.i18n&&(c.le="string"===typeof k.defaultCharset?k.defaultCharset:"string"===typeof k.characterSet?k.characterSet:"unknown");c.tv=ORA.analytics.versionStr;var d=ORA.common.QueryParamCache.getCache();this.addQueryParameters(d,c);!0===this.metatagAuto&&ORA.common.visitMetaTags(this.dcsMetaTagsAutoScrape,k,this.DCSext);
this.metanames&&ORA.common.visitMetaTags(this.dcsMetaTagArrScrape(this.metanames),k,this.DCSext)},dcsMetaTagArrScrape:function(c){return function(d,b,a){d=d.toLowerCase();-1!==c.indexOf(d)&&(a["meta_"+d]=b)}},dcsMetaTagsAutoScrape:function(c,d,b){0===c.indexOf("ORA.")?b[c]=d:0===c.indexOf("DCS.")?(c=c.split("DCS."),c[1]&&(b[c[1]]=d)):0===c.indexOf("DCSext.")&&(c=c.split("DCSext."),c[1]&&(b[c[1]]=d))},getPageAnalysis:function(){var c=ORA.analytics.dcsRef.dcsFPC(),d=ORA.common.extendArray;ORA.analytics.pageAnalysis?
d(["vt_f"]).forEach(function(b){ORA.analytics.pageAnalysis["WT."+b]&&delete ORA.analytics.pageAnalysis["WT."+b]}):ORA.analytics.pageAnalysis=ORA.analytics.dcsRef.genPageAnalysis();return ORA.paramsMerge(ORA.analytics.pageAnalysis,c)},genPageAnalysis:function(){try{if(ORA.fireEvent(new ORA.Event(ORA.Event.ANA_BEFORE_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS)),!ORA.analytics.isOptedOut()){var c=this.trackingData,d=this.DCS,b=this.DCSext,a=this.i18n;a&&(c.dep="");var f={},e;for(e in d)d.hasOwnProperty(e)&&
void 0!==d[e]&&"function"!==typeof d[e]&&(f[e]=d[e]);for(var g in c)c.hasOwnProperty(g)&&""!==c[g]&&void 0!==c[g]&&"function"!==typeof c[g]&&(f["WT."+g]=c[g]);for(var h in b)b.hasOwnProperty(h)&&""!==b[h]&&void 0!==b[h]&&"function"!==typeof b[h]&&(a&&(c.dep=0===c.dep.length?h:c.dep+";"+h),f[h]=b[h]);a&&0<c.dep.length&&(f["WT.dep"]=c.dep);ORA.Debug.superfine("pageAnalysis: "+this.prettify(f),"ANA");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_AFTER_PAGE_ANALYSIS,ORA.Event.STATUS_SUCCESS));return f}}catch(l){ORA.Debug.error("error in pageAnalyze: "+
l.toString())}},doRequest:function(){var c=this.destinations,d=this.getPageAnalysis;ORA.common.TrackingPipeline.registerMutation("analyticsAnnotate",function(b){if(b.params.mutation&&(!0===b.params.mutation.pageview||!0===b.params.mutation.conversion||!0===b.params.mutation.click||!0===b.params.mutation.collect&&!1!==b.params.sendSessionInfo||!0===b.params.mutation.view)){var a=d(),f;for(f in a)a.hasOwnProperty(f)&&!b.getParam(f)&&b.setParam(f,a[f]);b.setParam("ora.tag_id",ORA.getTagId());b.setParam("ora.tag_config",
ORA.getContextName());ORA.Debug.debug(b.params.desc?"annotating "+b.params.desc+" w/ analytics page analysis":"annotating w/ analytics page analysis","ANA");ORA.Debug.trace("annotating payload w/ "+ORA.analytics.prettify(a),"ANA");ORA.Debug.trace("Endpoints: "+ORA.analytics.prettify(c),"ANA");if("collect"!==b.params.desc)for(a=0;a<c.length;a++)b.endpoints.push({endpoint:c[a].endpoint,timeout:c[a].timeout,conf:ORA.analytics.dcsRef,protocolType:ORA.common.CommManager.GIF});ORA.fireEvent(new ORA.Event(ORA.Event.ANA_PV_MUTATE,
ORA.Event.STATUS_SUCCESS))}},1);ORA.Debug.debug("doRequest() - register mutation","ANA")},pageAnalyze:function(){ORA.Debug.trace("pageAnalyze()");this.dcsVar();this.adclickparam&&0<this.adclickparam.length&&this.dcsAdSearch();this.pageAnalyzehasRun=!0},getTime:function(){return(new Date).getTime()},dumpCounter:0,spinLock:function(c){for(var d=this.getTime();this.getTime()-d<c;)this.dumpCounter++},enQueue:function(c,d){var b=c;ORA.Debug.debug("enQueue() - action: "+JSON.stringify(b)+" msg: "+JSON.stringify(d),
"ANA");b||(b="collect");this.queue.push({action:b,message:d})},doAction:function(c){ORA.Debug.debug("doAction() - cmd: "+this.prettify(c),"ANA");var d="action_"+c.action;c=c.message;this.pageAnalyzehasRun||this.pageAnalyze();c.event&&!c.element&&(c.element=ORA.analytics.elemOfEvent(c.event,{A:1}));if(ORA.analytics.isFn(this[d]))this[d](c)},action_collect:function(c){ORA.Debug.debug("action_collect()","ANA");this.doRequest(c)},dcsIsOnsite:function(c,d){var b=c;if(0<b.length){b=b.toLowerCase();if(b===
window.location.hostname.toLowerCase())return!0;if(ORA.analytics.isFn(d.test))return d.test(b);if(0<d.length)for(var a=d.length,f=0;f<a;f++)if(b===d[f])return!0}return!1},dcsNavigation:function(c,d){var b="",a="",f=d.length,e;for(e=0;e<f;e++){var g=d[e];if(g.length&&(a=ORA.analytics.elemOfEvent(c,g),b=a.getAttribute&&a.getAttribute("id")?a.getAttribute("id"):"",a=a.className||"",b.length||a.length))break}return b.length?b:a},dcsAdSearch:function(){if(k.links){var c=this.adclickparam+"\x3d",d=c.length;
c=new RegExp(c,"i");var b=k.links.length,a=k.URL+"",f=a.search(c);if(-1!==f){var e=a.indexOf("\x26",f);var g=-1!==e?a.substring(f,e):a.substring(f,a.length);var h=new RegExp(g+"(\x26|#)","i")}for(a=0;a<b;a++)if(k.links[a].href){var l=k.links[a].href+"";g&&0<g.length&&(l=l.replace(h,"$1"));e=l.search(c);-1!==e&&(f=e+d,e=l.indexOf("\x26",f),e=-1!==e?l.substring(f,e):l.substring(f,l.length),this.trackingData.ad=this.trackingData.ad?this.trackingData.ad+";"+e:e)}}}};ORA.Debug.debug("dcs class loaded",
"ANA")})(window,window.document);
(function(m,k,c){ORA.analytics.find=function(d){ORA.analytics.selectorEngine||(ORA.analytics.selectorEngine=ORA.analytics.findSelector());return ORA.analytics.selectorEngine(d)};ORA.analytics.findSelector=function(){var d=/MSIE (\d+)/.exec(c.userAgent);d=d?d[1]:99;var b=k.body;if(k.querySelectorAll&&b&&8<d)return function(a){return b.querySelectorAll(a)};if(m.jQuery)return m.jQuery.find;if(m.Sizzle)return m.Sizzle;if(m.YAHOO&&YAHOO.util&&YAHOO.util.Selector)return YAHOO.util.Selector.query;if("qwery"in
m)return qwery;m.YUI&&YUI().use("node",function(a){return a.all});return k.querySelectorAll&&b?function(a){return b.querySelectorAll(a)}:function(){return[]}};ORA.Debug.debug("selectorEngine initialized","ANA")})(window,window.document,window.navigator);
(function(){var m={enable:!1,tagManager:"Google Tag Manager"},k=function(){try{var d=-1!==ORA.analyticsModule.prototype.postload.toString().indexOf("dataLayer")}catch(b){d=!1}d?ORA.Debug.debug("Tag Manager Plugin legacy postLoad found - not adding event","tagMgr"):"undefined"!==typeof window.dataLayer?(window.dataLayer.push({event:"ora.load"}),ORA.Debug.debug("Tag Manager Plugin sending ready event to GTM","tagMgr")):ORA.Debug.debug("Tag Manager Plugin - no GTM dataLayer found","tagMgr")},c=function(d,
b){var a=b||function(){},f=d&&d.config||{};m=ORA.common._shallowMerge(m,f);void 0===f.enable||f.enable?(ORA.analytics.dcsRef.config.s_disableSeed=!0,ORA.common.TrackingPipeline.disableSeed(),ORA.Debug.debug("Tag Manager Plugin disabling seed event","tagMgr"),"Google Tag Manager"===m.tagManager&&ORA.addEventHandler(ORA.Event.ANA_PRODUCT_READY,k,null,!0),a(),ORA.Debug.debug("Tag Manager Plugin init complete","tagMgr")):(ORA.Debug.debug("Tag Manager Plugin is disabled, exiting","tagMgr"),a())};ORA.Debug.debug("Tag Manager - Registering Plugin",
"tagMgr");ORA.regPlugin("tagMgr",c,{blockCollect:!0});ORA.analytics.plugins.tagMgr={};ORA.analytics.plugins.tagMgr.init=c;ORA.analytics.plugins.tagMgr.testNode=function(d){return eval(d)}})();ORA.setExecuteState("analytics","ready");ORA.fireEvent(new ORA.Event(ORA.Event.ANA_LOAD_COMPLETE,ORA.Event.STATUS_SUCCESS),!0);